### ISSUE TITLE
Parasoul CA, SA, MA labelled Prestige and Name Search Issue.

### ISSUE THREAD

**Issue by WildSnail913** [Krazete/sgm#4] opened 2024-01-03 13:12 UTC
1. Every Parasoul's Character Ability, Signature Ability, and Marquee Ability fields are labelled Prestige Ability instead.

2. Typing `Seraph ` into the search bar with Variant Name selected returns Megalomaniac (in addition to Seraph Soldier).

**Comment by Krazete** [comment] 2024-01-05 02:26
1. Fixed with 7709ca5.  
*(Cause: Ability titles are defined by class name `ca`, `sa`, `pa`, or `ma`; and all Parasoul cards have a `pa` classname. I fixed this before for Marie/`ma` by making the CSS stricter but forgot to fix it for Parasoul too.)*
2. This is functioning as intended. Searching via Variant Name also searches by Variant ID, and the game's internal ID for Megalomaniac is `sSeraph`. ("Sans Seraph" was likely the in-development placeholder name for this variant.)

**Closed as completed by Krazete** 2024-01-05 02:26 UTC
